export const ATHENA_QUOTA = { ANON: { limit: 5, windowMs: 6 * 60 * 60 * 1000, name: "athena-anon" }, AUTH: { limit: 40, windowMs: 6 * 60 * 60 * 1000, name: "athena-auth" }, ANON_CONCURRENCY_CAP: 3 } as const;
const store = new Map<string, number[]>();
const MAX_STORE_SIZE = 20_000;
const MAX_IDENTIFIER_LENGTH = 256;
let anonInFlight = 0;
function cleanup(key: string, windowMs: number): number[] { const cutoff = Date.now() - windowMs; const entries = store.get(key) ?? []; const filtered = entries.filter((ts) => ts > cutoff); if (filtered.length) store.set(key, filtered); else store.delete(key); return filtered; }
function pruneIfNeeded(): void { if (store.size <= MAX_STORE_SIZE) return; const cutoff = Date.now() - Math.max(ATHENA_QUOTA.ANON.windowMs, ATHENA_QUOTA.AUTH.windowMs); for (const [key, timestamps] of store) { const filtered = timestamps.filter((ts) => ts > cutoff); if (filtered.length) store.set(key, filtered); else store.delete(key); } if (store.size > MAX_STORE_SIZE) { const excess = store.size - MAX_STORE_SIZE; let removed = 0; for (const key of store.keys()) { store.delete(key); if (++removed >= excess) break; } } }
export interface QuotaCheckResult { allowed: boolean; tier: "anon" | "auth"; remaining: number; resetAt: number; retryAfter: number; concurrencyBlocked: boolean; requiresSignIn: boolean; }
export function checkAthenaQuota(tier: "anon" | "auth", identifier: string): QuotaCheckResult { if (tier === "anon" && anonInFlight >= ATHENA_QUOTA.ANON_CONCURRENCY_CAP) return { allowed: false, tier, remaining: 0, resetAt: 0, retryAfter: 5, concurrencyBlocked: true, requiresSignIn: false }; const cfg = tier === "anon" ? ATHENA_QUOTA.ANON : ATHENA_QUOTA.AUTH; const safeIdentifier = identifier.slice(0, MAX_IDENTIFIER_LENGTH); const key = `${tier}:${safeIdentifier}`; const now = Date.now(); const entries = cleanup(key, cfg.windowMs); if (entries.length >= cfg.limit) { const oldest = Math.min(...entries); const resetTime = oldest + cfg.windowMs; pruneIfNeeded(); return { allowed: false, tier, remaining: 0, resetAt: Math.floor(resetTime / 1000), retryAfter: Math.max(1, Math.ceil((resetTime - now) / 1000)), concurrencyBlocked: false, requiresSignIn: tier === "anon" }; } entries.push(now); store.set(key, entries.slice(-cfg.limit)); pruneIfNeeded(); return { allowed: true, tier, remaining: Math.max(0, cfg.limit - entries.length), resetAt: Math.floor((now + cfg.windowMs) / 1000), retryAfter: 0, concurrencyBlocked: false, requiresSignIn: false }; }
export function reserveAnonSlot(): void { anonInFlight = Math.min(anonInFlight + 1, ATHENA_QUOTA.ANON_CONCURRENCY_CAP); }
export function releaseAnonSlot(): void { anonInFlight = Math.max(0, anonInFlight - 1); }
export function peekAthenaQuota(tier: "anon" | "auth", identifier: string): Omit<QuotaCheckResult, "allowed" | "retryAfter" | "concurrencyBlocked" | "requiresSignIn"> { const cfg = tier === "anon" ? ATHENA_QUOTA.ANON : ATHENA_QUOTA.AUTH; const key = `${tier}:${identifier.slice(0, MAX_IDENTIFIER_LENGTH)}`; const entries = cleanup(key, cfg.windowMs); return { tier, remaining: Math.max(0, cfg.limit - entries.length), resetAt: Math.floor((Date.now() + cfg.windowMs) / 1000) }; }
