/** Cloudflare Workers AI service with module routing, token caps, and scoped rate limits. */
const CF_ACCOUNT_ID = process.env.CLOUDFLARE_ACCOUNT_ID || "";
const CF_AI_TOKEN = process.env.CLOUDFLARE_AI_TOKEN || process.env.CF_API_TOKEN || "";
const CF_BASE = `https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/ai/run`;
const INFERENCE_TIMEOUT_MS = 20_000;
export const AI_MODELS = { FAST:"@cf/meta/llama-3.3-70b-instruct-fp8-fast", REASONING:"@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", FALLBACK:"@cf/openai/gpt-oss-120b", VISION:"@cf/meta/llama-3.2-11b-vision-instruct" } as const;
export type AiTier = "jjc"|"intern"|"cofounder"|"founder"|"azodobz";
const TIER_MULTIPLIER:Record<AiTier,number>={jjc:1,intern:1,cofounder:2,founder:4,azodobz:Infinity};
export const MODULE_TOKEN_CAPS={e1_deck:8192,e2_script:2048,e3_live:1536,e4_full:8192,e5_founder:2048,e5_founder_deep:8192} as const;
const WINDOW_MS=60_000,WINDOW_REQUESTS=12,WINDOW_TOKENS=32_768;
const usage=new Map<string,{started:number;requests:number;tokens:number}>();
export interface ModuleModelConfig{textModel:string;visionModel:string;maxTokens:number;deepMaxTokens?:number;}
export const MODULE_MODEL_MAP:Record<string,ModuleModelConfig>={e1_deck:{textModel:AI_MODELS.FAST,visionModel:AI_MODELS.VISION,maxTokens:8192},e2_script:{textModel:AI_MODELS.FAST,visionModel:AI_MODELS.VISION,maxTokens:2048},e3_live:{textModel:AI_MODELS.FAST,visionModel:AI_MODELS.VISION,maxTokens:1536},e4_full:{textModel:AI_MODELS.REASONING,visionModel:AI_MODELS.VISION,maxTokens:8192},e5_founder:{textModel:AI_MODELS.FAST,visionModel:AI_MODELS.VISION,maxTokens:2048,deepMaxTokens:8192}};
export type ModuleModelKey=keyof typeof MODULE_MODEL_MAP;
export const SCORING_WEIGHTS={problemClarity:.15,solutionClarity:.15,marketOpportunity:.12,businessModel:.13,teamCredibility:.10,traction:.10,financials:.10,askClarity:.15} as const;
export function computeWeightedOverall(scores:Record<string,number|null>):number|null{let total=0,weightSum=0;for(const[key,weight]of Object.entries(SCORING_WEIGHTS)){const value=scores[key];if(typeof value==="number"&&value>=0&&value<=100){total+=value*weight;weightSum+=weight;}}return weightSum?Math.round(total/weightSum):null;}
export function validateScoreConsistency(scores:Record<string,number|null>):boolean{return Object.values(scores).every((v)=>typeof v!=="number"||(v>=0&&v<=100));}
interface ChatMessage{role:"system"|"user"|"assistant";content:string;}
export interface CallOptions{maxTokens?:number;temperature?:number;model?:string;moduleKey?:string;tier?:AiTier;scopeKey?:string;deep?:boolean;}
function capFor(moduleKey:string|undefined,requested:number,deep:boolean):number{const config=moduleKey&&MODULE_MODEL_MAP[moduleKey];const cap=deep&&config?.deepMaxTokens?config.deepMaxTokens:config?.maxTokens||8192;return Math.min(Math.max(256,Math.floor(requested)),cap);}
export function enforceTokenBudget(moduleKey:string|undefined,requested:number,tier:AiTier="jjc",deep=false,scopeKey="anonymous"):number{const cap=capFor(moduleKey,requested,deep);const key=`${scopeKey}:${tier}:${moduleKey||"generic"}`;const now=Date.now();const prior=usage.get(key);const state=!prior||now-prior.started>=WINDOW_MS?{started:now,requests:0,tokens:0}:prior;const multiplier=TIER_MULTIPLIER[tier]||1;if(multiplier!==Infinity&&(state.requests>=WINDOW_REQUESTS*multiplier||state.tokens+cap>WINDOW_TOKENS*multiplier))throw new Error("AI rate limit exceeded; retry after the current minute window");state.requests++;state.tokens+=cap;usage.set(key,state);return cap;}
export async function callAI(messages:ChatMessage[],options:CallOptions={}):Promise<string>{const moduleKey=options.moduleKey;const model=options.model||(moduleKey?MODULE_MODEL_MAP[moduleKey]?.textModel:AI_MODELS.FAST);const maxTokens=enforceTokenBudget(moduleKey,options.maxTokens||8192,options.tier,options.deep,options.scopeKey);const temperature=options.temperature??(moduleKey==="e3_live"?.2:moduleKey==="e4_full"?.3:.5);if(!CF_ACCOUNT_ID||!CF_AI_TOKEN)throw new Error("Cloudflare AI not configured");try{return await callModel(model,messages,maxTokens,temperature);}catch(primaryError){try{return await callModel(process.env.CLOUDFLARE_AI_FALLBACK_MODEL||AI_MODELS.FALLBACK,messages,maxTokens,temperature);}catch(fallbackError){console.error("[AI] primary and fallback failed",{primaryError,fallbackError});throw fallbackError;}}}
async function callModel(model:string,messages:ChatMessage[],maxTokens:number,temperature:number):Promise<string>{const response=await fetch(`${CF_BASE}/${model}`,{method:"POST",headers:{Authorization:`Bearer ${CF_AI_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify({messages,max_tokens:maxTokens,temperature}),signal:AbortSignal.timeout(INFERENCE_TIMEOUT_MS)});if(!response.ok)throw new Error(`Cloudflare AI error ${response.status}: ${(await response.text()).slice(0,200)}`);const data=await response.json() as any;if(!data.success)throw new Error(`Cloudflare AI failed: ${JSON.stringify(data.errors)}`);const result=data.result;if(result?.response)return result.response;if(result?.message?.content)return result.message.content;if(result?.choices?.[0]?.message?.content)return result.choices[0].message.content;return typeof result==="string"?result:JSON.stringify(result);}
export async function callAIVision(prompt:string,imageBase64:string,options:CallOptions={}):Promise<string>{const imageDataUri=imageBase64.startsWith("data:")?imageBase64:`data:image/png;base64,${imageBase64}`;const maxTokens=enforceTokenBudget(options.moduleKey,options.maxTokens||8192,options.tier,options.deep,options.scopeKey);if(!CF_ACCOUNT_ID||!CF_AI_TOKEN)throw new Error("Cloudflare AI not configured");const response=await fetch(`${CF_BASE}/${AI_MODELS.VISION}`,{method:"POST",headers:{Authorization:`Bearer ${CF_AI_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify({messages:[{role:"system",content:"You are an expert pitch coach and presentation analyst."},{role:"user",content:[{type:"text",text:prompt},{type:"image_url",image:{url:imageDataUri}}]}],max_tokens:maxTokens}),signal:AbortSignal.timeout(INFERENCE_TIMEOUT_MS)});if(!response.ok)throw new Error(`Cloudflare Vision AI error ${response.status}: ${(await response.text()).slice(0,200)}`);const data=await response.json() as any;if(!data.success)throw new Error(`Cloudflare Vision AI failed: ${JSON.stringify(data.errors)}`);const result=data.result;return result?.response||result?.message?.content||JSON.stringify(result);}
export async function executeWithFallback<T>(primaryFn:()=>Promise<T>,fallbackFn?:()=>Promise<T>,_moduleKey?:string):Promise<T>{try{return await primaryFn();}catch(primaryError){if(!fallbackFn)throw primaryError;try{return await fallbackFn();}catch(fallbackError){console.error("[AI] fallback failed",{primaryError,fallbackError});throw fallbackError;}}}
export function getAIConfigStatus(){return{configured:!!(CF_ACCOUNT_ID&&CF_AI_TOKEN),provider:"Cloudflare Workers AI",models:Object.values(AI_MODELS),tokenCaps:MODULE_TOKEN_CAPS,rateLimit:{windowMs:WINDOW_MS,requests:WINDOW_REQUESTS,tokens:WINDOW_TOKENS}};}
