/** Cloudflare Workers AI service. */
const CF_ACCOUNT_ID = process.env.CLOUDFLARE_ACCOUNT_ID || "";
const CF_AI_TOKEN = process.env.CLOUDFLARE_AI_TOKEN || process.env.CF_API_TOKEN || "";
const CF_BASE = `https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/ai/run`;
const INFERENCE_TIMEOUT_MS = 20_000;
export const AI_MODELS = { TEXT_PRIMARY: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", TEXT_FALLBACK: "@cf/openai/gpt-oss-120b", TEXT_FAST: "@cf/meta/llama-3.2-3b-instruct", VISION: "@cf/meta/llama-3.2-11b-vision-instruct" } as const;
export interface ModuleModelConfig { textModel: string; visionModel: string; }
export const MODULE_MODEL_MAP: Record<string, ModuleModelConfig> = Object.fromEntries(["e1_deck", "e2_script", "e3_live", "e4_full", "e5_founder"].map((key) => [key, { textModel: AI_MODELS.TEXT_PRIMARY, visionModel: AI_MODELS.VISION }])) as Record<string, ModuleModelConfig>;
export type ModuleModelKey = keyof typeof MODULE_MODEL_MAP;
export const SCORING_WEIGHTS = { problemClarity: .15, solutionClarity: .15, marketOpportunity: .12, businessModel: .13, teamCredibility: .10, traction: .10, financials: .10, askClarity: .15 } as const;
export function computeWeightedOverall(scores: Record<string, number | null>): number | null { let total=0, weightSum=0; for (const [key, weight] of Object.entries(SCORING_WEIGHTS)) { const val=scores[key]; if (typeof val === "number" && val >= 0 && val <= 100) { total += val * weight; weightSum += weight; } } return weightSum ? Math.round(total / weightSum) : null; }
export function validateScoreConsistency(scores: Record<string, number | null>): boolean { return Object.values(scores).every((val) => typeof val !== "number" || (val >= 0 && val <= 100)); }
interface ChatMessage { role: "system" | "user" | "assistant"; content: string; }
export async function callAI(messages: ChatMessage[], options: { maxTokens?: number; temperature?: number; model?: string } = {}): Promise<string> { const model=options.model||AI_MODELS.TEXT_PRIMARY, maxTokens=options.maxTokens||8192, temperature=options.temperature??.7; if (!CF_ACCOUNT_ID || !CF_AI_TOKEN) throw new Error("Cloudflare AI not configured — set CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_AI_TOKEN"); try { return await callModel(model,messages,maxTokens,temperature); } catch (primaryError) { if (model===AI_MODELS.TEXT_PRIMARY) { console.warn(`[AI] Primary model ${model} failed, trying fallback ${AI_MODELS.TEXT_FALLBACK}...`, primaryError); try { return await callModel(AI_MODELS.TEXT_FALLBACK,messages,maxTokens,temperature); } catch (fallbackError) { console.error("[AI] Fallback model also failed", fallbackError); throw fallbackError; } } throw primaryError; } }
async function callModel(model: string, messages: ChatMessage[], maxTokens: number, temperature: number): Promise<string> { const response=await fetch(`${CF_BASE}/${model}`, { method:"POST", headers:{Authorization:`Bearer ${CF_AI_TOKEN}`,"Content-Type":"application/json"}, body:JSON.stringify({messages,max_tokens:maxTokens,temperature}), signal:AbortSignal.timeout(INFERENCE_TIMEOUT_MS) }); if (!response.ok) throw new Error(`Cloudflare AI error ${response.status}: ${(await response.text()).slice(0,200)}`); const data=await response.json() as any; if (!data.success) throw new Error(`Cloudflare AI failed: ${JSON.stringify(data.errors)}`); const result=data.result; if (result?.response) return result.response; if (result?.message?.content) return result.message.content; if (result?.choices?.[0]?.message?.content) return result.choices[0].message.content; return typeof result === "string" ? result : JSON.stringify(result); }
export async function callAIVision(prompt: string, imageBase64: string, options: { maxTokens?: number } = {}): Promise<string> { if (!CF_ACCOUNT_ID || !CF_AI_TOKEN) throw new Error("Cloudflare AI not configured — set CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_AI_TOKEN"); const imageDataUri=imageBase64.startsWith("data:")?imageBase64:`data:image/png;base64,${imageBase64}`; const response=await fetch(`${CF_BASE}/${AI_MODELS.VISION}`, { method:"POST", headers:{Authorization:`Bearer ${CF_AI_TOKEN}`,"Content-Type":"application/json"}, body:JSON.stringify({messages:[{role:"system",content:"You are an expert pitch coach and presentation analyst."},{role:"user",content:[{type:"text",text:prompt},{type:"image_url",image:{url:imageDataUri}}]}],max_tokens:options.maxTokens||8192}), signal:AbortSignal.timeout(INFERENCE_TIMEOUT_MS) }); if (!response.ok) throw new Error(`Cloudflare Vision AI error ${response.status}: ${(await response.text()).slice(0,200)}`); const data=await response.json() as any; if (!data.success) throw new Error(`Cloudflare Vision AI failed: ${JSON.stringify(data.errors)}`); const result=data.result; return result?.response||result?.message?.content||JSON.stringify(result); }
export async function executeWithFallback<T>(primaryFn:()=>Promise<T>, _fallbackFn?:()=>Promise<T>, _moduleKey?:string):Promise<T>{return primaryFn();}
export function getAIConfigStatus(){return {configured:!!(CF_ACCOUNT_ID&&CF_AI_TOKEN),provider:"Cloudflare Workers AI",models:Object.values(AI_MODELS)};}
