import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { askAthenaWithTools, AthenaMessage } from "@/lib/athena-agent";
import { prisma } from "@/lib/db";
import { fetchMemory } from "@/lib/memory/memory";
import { checkAthenaQuota, reserveAnonSlot, releaseAnonSlot, ATHENA_QUOTA } from "@/lib/athena-quota";
import { getClientIp, getDeviceFingerprint } from "@/lib/security";
export const runtime = "nodejs"; export const dynamic = "force-dynamic"; export const maxDuration = 60;
function quotaHeaders(result: { tier: "anon" | "auth"; remaining: number; resetAt: number; retryAfter?: number; requiresSignIn?: boolean }) { return { "X-Athena-Tier": result.tier, "X-Athena-Remaining": String(result.remaining), "X-Athena-Reset": String(result.resetAt), ...(result.requiresSignIn ? { "X-Athena-Requires-Sign-In": "1" } : {}), ...(result.retryAfter ? { "Retry-After": String(result.retryAfter) } : {}) }; }
export async function POST(request: NextRequest) {
  const { userId } = await auth(); let body: unknown; try { body = await request.json(); } catch { return NextResponse.json({ error: "Invalid JSON" }, { status: 400 }); }
  const { message, history, context, reasoning, tier } = (body ?? {}) as { message?: unknown; history?: unknown; context?: unknown; reasoning?: unknown; tier?: unknown };
  if (!message || typeof message !== "string") return NextResponse.json({ error: "Message required" }, { status: 400 }); if (message.length > 2000) return NextResponse.json({ error: "Message too long (max 2000 chars)" }, { status: 400 });
  const runtimeTier = tier === "deep" || tier === "diligence" ? tier : "conversational"; const options = { reasoning: reasoning === true, tier: runtimeTier as "conversational" | "diligence" | "deep" };
  const quotaTier: "anon" | "auth" = userId ? "auth" : "anon"; const identifier = userId || `${getClientIp(request)}:${await getDeviceFingerprint(request)}`; const quota = checkAthenaQuota(quotaTier, identifier);
  if (!quota.allowed) { const status = quota.requiresSignIn ? 402 : 429; return NextResponse.json({ error: quota.concurrencyBlocked ? "athena_busy" : "athena_quota_exceeded", message: quota.concurrencyBlocked ? "Athena is helping other visitors right now. Please try again in a moment." : quota.requiresSignIn ? "You've reached Athena's free visitor limit. Sign in to keep chatting — it's free." : "You've reached Athena's chat limit for now. Please try again later.", retryAfter: quota.retryAfter, remaining: 0, resetAt: quota.resetAt, tier: quota.tier, requiresSignIn: quota.requiresSignIn }, { status, headers: quotaHeaders(quota) }); }
  const isAnon = quotaTier === "anon"; if (isAnon) reserveAnonSlot();
  try { let internalUserId: string | undefined; const memory = userId ? await fetchMemory(userId, 2) : { source: "empty" as const, sessions: [], context: "No prior pitch sessions are available." }; if (userId) internalUserId = (await prisma.user.findUnique({ where: { clerkId: userId }, select: { id: true } }))?.id; const supplied = context as { firstName?: string; currentModule?: string; currentPage?: string; plan?: string } | null; const ctx = { userId, internalUserId, firstName: supplied?.firstName, currentModule: supplied?.currentModule, currentPage: supplied?.currentPage, plan: supplied?.plan, memorySource: memory.source, memory: memory.context }; const enrichedMessage = `[ATHENA_MEMORY source=${memory.source}]\n${memory.context}\n[/ATHENA_MEMORY]\n${message}`; const response = await askAthenaWithTools(enrichedMessage, ctx, (history as AthenaMessage[]) ?? [], options); return NextResponse.json({ response, timestamp: new Date().toISOString(), tier: quotaTier, remaining: quota.remaining, resetAt: quota.resetAt, memorySource: memory.source, nudgeSignIn: quotaTier === "anon" && quota.remaining <= ATHENA_QUOTA.ANON.limit - 2 }, { status: 200, headers: quotaHeaders({ tier: quotaTier, remaining: quota.remaining, resetAt: quota.resetAt }) }); }
  catch (error) { console.error("[Athena Chat] Provider failure; serving static fallback", error); return NextResponse.json({ response: "I’m having trouble reaching the AI service right now. Your request is safe—please try again in a moment, or start with a new pitch question.", timestamp: new Date().toISOString(), tier: quotaTier, remaining: quota.remaining, resetAt: quota.resetAt, fallback: true }, { status: 200, headers: quotaHeaders({ tier: quotaTier, remaining: quota.remaining, resetAt: quota.resetAt }) }); } finally { if (isAnon) releaseAnonSlot(); }
}
